name: Build, Test, and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v7
      with:
        dotnet-version: '7.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release

    - name: Package
      run: |
        mkdir packages
        cp -R ./Curseforge-folderizer/bin/Release/net7.0/* ./packages/
        zip -r "./packages/Curseforge-folderizer-$(date +'%Y%m%d').zip" ./packages/*

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: your-project-artifact
        path: ./packages/Curseforge-folderizer-*.zip
